version: '3.7'

services:
  registry:
    image: registry:2
    expose:
      - 5000

  buildkitd:
    image: moby/buildkit:rootless
    privileged: true
    command: "--addr tcp://0.0.0.0:3242"
    expose:
      - 3242

  db:
    image: mysql
    command: "--default-authentication-plugin=mysql_native_password"
    env_file: .env
    expose:
      - 3306

  service-manager:
    build: .
    image: service-manager
    ports:
      - 8080:8080
    env_file: .env
    links:
      - db
      - buildkitd
      - registry
    environment:
      - PORT=8080
      - BUILDKIT_HOST=tcp://buildkitd:3242
