apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-manager-buildkitd-deployment
  labels:
    app: service-manager-buildkitd
spec:
  selector:
    matchLabels:
      app: service-manager-buildkitd
  template:
    metadata:
      labels:
        app: service-manager-buildkitd
    spec:
      restartPolicy: Always
      containers:
        - name: buildkitd
          image: moby/buildkit:rootless
          args:
            - --addr
            - tcp://0.0.0.0:3242
          ports:
            - containerPort: 3242
---
apiVersion: v1
kind: Service
metadata:
  name: service-manager-buildkitd-service
spec:
  ports:
  - port: 3242
    targetPort: 3242
  selector:
    app: service-manager-buildkitd
