apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-manager-database-deployment
  labels:
    app: service-manager-database
spec:
  selector:
    matchLabels:
      app: service-manager-database
  template:
    metadata:
      labels:
        app: service-manager-database
    spec:
      restartPolicy: Always
      containers:
        - name: database
          image: mysql
          args:
            - --default-authentication-plugin=mysql_native_password
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: servicemanager
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: rootpassword
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: user
---
apiVersion: v1
kind: Service
metadata:
  name: service-manager-database-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: service-manager-database
