kind: PersistentVolume
apiVersion: v1
metadata:
  name: service-manager-db-pv
  labels:
    type: local
    app: service-manager-db
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/servicemanager/db/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: service-manager-db-pvc
  labels:
    app: service-manager-db
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-manager-database-deployment
  labels:
    app: service-manager-database
spec:
  selector:
    matchLabels:
      app: service-manager-database
  template:
    metadata:
      labels:
        app: service-manager-database
    spec:
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: service-manager-db-pvc
      containers:
        - name: database
          image: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
          args:
            - --default-authentication-plugin=mysql_native_password
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: servicemanager
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: rootpassword
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: user
---
apiVersion: v1
kind: Service
metadata:
  name: service-manager-database-service
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: service-manager-database
